### ISSUE TITLE
Create Settings Page

### ISSUE THREAD

**Issue by jared-leddy** [WPFedora/WordPress-Fedora#3]
This would feel alot cleaner if it was setup on a dedicated settings page instead of just lumped in with the core settings. This would have a better UX, but also keep reminding people every time they see it that they are using WP Fedora.

![image](https://github.com/user-attachments/assets/699e83a6-c5c5-4ed7-ace0-08a78078b4df)

**Comment by GoogleSEOMastermind** [comment]
This could definitely be an option. Currently, I'm appending settings to existing admin pages to avoid creating new pages, which would require additional code, potential security measures, and maintenance

By using the existing settings structure, we can keep things lightweight and simple, reducing the risk of security issues for admin permissions while still providing the necessary functionality

Really depends on what the community wants in a lot of ways, to be sure

**Comment by jared-leddy** [comment]
Yeah man. Throwing them all in settings is great for day 1, but as time goes on it's probably better to have your own options page. Especially with the latest update exceeding the settings arena, it's kind of on the cusp of making that change. It could be a really good idea to centralize everything for this plugin in one place.

Here is a screenshot of the SEO Press plugin. They have the sidebar menu item, but they also have their own page menu. We could do something similar where you have 1 page for everything and just toggle between the page menu items. 

It's definitely adding more into the plugin. We've kind of already crossed that threshold of "lightweight and simple". 

This would be about making it pretty, which really puts a stamp on this having longevity. Which increases the UX and overall satisfaction of the product. Thus, further increasing recommendations and downloads. 

We could use something like React or Vue to keep the size down, but UI/UX could significantly be improved.

<img width="500" alt="image" src="https://github.com/user-attachments/assets/90acbb03-e468-46f8-969c-8318ae558d7e">

**Comment by jared-leddy** [comment]
Rejected by user preference.
