### ISSUE TITLE
Add Feature Request Link in Plugin

### ISSUE THREAD

**Issue by jared-leddy** [WPFedora/WordPress-Fedora#4]
We should add a link for feature requests in the plugin, and use the Github issues link for that. This will start to drive traffic to the Github repo and start educating the audience on how to communicate with you.

[https://github.com/WPFedora/WordPress-Fedora/issues/](https://github.com/WPFedora/WordPress-Fedora/issues/)

**Comment by GoogleSEOMastermind** [comment]
Sounds wonderful! Since this is community driven, the more input/ideas/assistance we can get, the easier it will be to develop with users in mind

**Comment by jared-leddy** [comment]
This has been added to the footer.
